spring:
  application:
    name: eureka-server

server:
  port: 10001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
    #实例是否在eureka服务器上注册自己的信息以提供其他服务发现,默认为true
    register-with-eureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息,默认为true
    fetch-registry: false
  server:
    #开启自我保护模式
    enable-self-preservation: false
    #清理无效节点,默认60*1000毫秒,即60秒
    eviction-interval-timer-in-ms: 5000

